# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.8.3"
      addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: "m0yWdlZD2xi7S6pNnfurUPEq4ZprDC0t5mGGKbN/0OniNDzjor/G+ylC6JWYBy4fqKXmCGlyfH1uVcl2wjVBbj3zdimfAF+31Dcdeed9srKb6ZZsC9ZnS8FJHqRESAxyX2fV4jWpwYjy1ffgGpkE2BRddBC3P3AxJSDHpKo8lQ66uwgiM5StR1PAp1UTVsqfNOhPc8aD5jYhgLUNYXA1/3ytfR/52B4Lk9Y0GN1o5NAYHsHu0zvUibreJBlkk+5YOYC9INaRNn4v9ulP+eqOeSDLl7phQjZpsLXnx/46EzyQXoV2cTfIlsHk2kTdj1jKvXzGmUK6lDMammnuba/OGRJigj8Uo1/XOxsz1E3IspmSIqJkrhAJdbjI9Lu9VwvDJq5uDQw0rZi/dsHIEPWk0kIcaC3kRE7YEOKKfY3llG+JsKGi2+QKeH4dc3BjPgLMXWdhCQXep8GtKlLxwMjsSsLC++FcGfXP5GWgDcCF6E7MFgOjebtxnuC2TwNmZDn1+5EMmbHZfUszUMUA/apx9Ix2KsH83GDqWGybjIjE/7tG9M1kFfHA9xKsFs39/f7LNvMf6ukMgqaWF4oI7d6c0N8fPej+7p1TDgrrVxfJvS74Oe6sD3kbVXglMfSOUZa/yF7hBfzW6ae/v8cEvN/jal24Hvypt/kQ7pA7fkfxMg0="
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - cd gaejosim
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ..
        - cd .. && sonar-scanner

    - language: node_js
      node_js: 14
      install:
        - cd frontend
        - cd gaejosim
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
