# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.8.3"
      addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: "WkSKZttYe/1FB57AQL0NdgDAr8Tt74IDatkx8ovdZAPZdaGaJJUNj6iJtecLJ3lIO54hTRFv8UYViczv1X20bFvrTJROjoMYBiv0lghh/SjTQFYEBB0H6YvmxB6qCNeYvviH8R+8iu43xcjSyEzYnmuSDzV2CE5t2cX3tj/+mXJjGw5Ja1lw+S+f8dDegl1CpbnVl63qkJTln0xxJK8m029kX/o0TAE0QZv3pSrFvhd+CRG735obrWcL/5pugl/nTvN1y+vgHah9XySa6DsPDPkh6Q7qqWe2OOHR+/GN8rPmWYD9UmAsS/A6gkYdUSN7neExeGgNtU4OQ7ohoQfNgNkNN29XYhOz/z6JKYW3dTfMRNpCmfkp36tXeOf1qET0VjHQGGu8hjcid97taIj5aT6U4XXmejVAr0DoY/8kwDd5oELonOQdNDo11AOZvhGzkpKLAkH5Zp5INgHsxGsB27jEkHsDKepsbqqVGiofanLcGqJT765z2c/or6Q//PxDmTfY3E4jTGmtm8LLfG7YdzqmTEqG+RCpSf6JCZd7pLN+crf5zzVZee9ruQqSYgRJ5SlbjEItHAjJgKjTUnlS25qaTjSdHkJH78+zYnWSj2hJIlGniPx7aO5rj/8zvxmYPxDZGYKjQuukSlIWJwRmAa2DFre+LKSQLXtkNDkhxa8="
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - cd gaejosim
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ../.. && sonar-scanner

    - language: node_js
      node_js: 14
      install:
        - cd frontend
        - cd gaejosim
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
