# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.8.3"
      addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: "nfX4B/myUOdMIrwF/qDRgwzZuxjghy5/vyMbR+FYdgmCqmBcCoL0sICzmDwGDihgi/vhfnWd4xnVFOddYtWVxGsmfUjSjKG2wRdJqJ8sTjvBvNHAT3bkHLc/D4QX0pFnN8ueQY5g4QCq1L0kVa3pMx51Z5edWcGKBzlibHWy2wZ8RfTvH0TW7TSll9KHgCH+/KwTaH9oC7xlowWTKeyjTXeSxgD5dq6S982FMnRjW4pwgR/lMYaS3HgG+A22VRkNL5feUF3UdBglrixEzOFFCK15/PznhUW76bxAxducip2C93Fcazz02TOcvCdxWvX1Zu3VI9ZJ6TbLtNkdjlndEMi8DqcofBOf35EZU/0O6aD3mruHJA6qkunbpqJ8xydSDTF6p/167Ea3mHY3h7uL+s9pDBxHLLGSotbsLehYGrXsrkQRdQSR8bu8xl2NW0RMTlEA4rzsmNaqzZKcPaiIYE3/nAqoQ+ofqWuyyT/vFJ0XTZOk9Z5TsHqOYGV0XOv7rnGahKOTyBSSgt+bLQTeIKq/nUor54n1RyBSg8fXsPXW35tpzfLHU83+M3r4by4C9rTlkEwrDsprbMD9Rs3sAD25Z7Ijgvq/i3JK3zQhKBsG3nlVSuDG4KKDpicZK8nRkfxn6sc8h/Qz0h/yvmEmTn5dlwI6P5RM9x78nnqo1G4="
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - cd gaejosim
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ../.. && sonar-scanner

    - language: node_js
      node_js: 14
      install:
        - cd frontend
        - cd gaejosim
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
