# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.8.3"
      addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: "ZNNNncAC+MMLhNLa1bB/neDW/sq7YyJxTeNKFsj81JFpLkvcDheRoqqXy86+g99xJVeoWbcZRtWBEZdcjz8V9oklR9DyIYcH4fMLdaOIfZRq+Z7GLuIQNVyccY2IdvuWBokd5JFCT8Zh6dhyOtS/tE02bdqbJsMetc5KTo6iEwy8b/cl3ywxaJqq/NYZJxohDVPoG8xkVDhKq6hGz1qQKr6DM3jlPjAiChmvfqt8ZCdd/GNoPX0/ICS8ArdVtZOrzdVj9K07KqnsTln+fJDZSt80kIrxEraDCOyqCGubH1sZA4gvcwDIbHNrvpkwTsO5JTbvKyi127dMY43vRdfrQh0j5MIETC/cJ4yO+7iYsaXCwe2RXGdpWdJh24NlcFSZs4L9L+ZoZAODU4kq3dPlwHVWLCO7w6CwRMCDilcu4zFsxzvDtb3SXYviYrcvikk0uRcTZUnFcFkeILAKuif5oGLn0IqRTfEJZQwgFPa0B1H7qbdBT0DQyZUNAX7JUznZ/Q1qkXyUz0nBAoNL3gmXNpC3C+gOKKIRYFXZTG8S8FpoX/J3FgUFEwysWvGhp+6R9JuDG+/jLB9SGYfHWs9Wm1Fj6JwsjnI3dVg4PJ3HY/PBqBsaXP5Oua6O7ZIu9k2XNYoE7L6aAKr/WUu8OrYOESMEntqWJspYw8D9y73PPoI="
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - cd gaejosim
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ../.. && sonar-scanner

    - language: node_js
      node_js: 14
      install:
        - cd frontend
        - cd gaejosim
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
