version: "3.8"

services:
  gaejosim:
    image: docker.pkg.github.com/swsnu/swpp2021-team3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
    ports:
      - "8000:8000"
    env_file:
      - ./.secrets/base.json
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10